## Algorithm to map the neighbourhoods in Toronto

The datset is not readily availaable, hence needs to be scraped.

## Data Collection and Pre-processing

### Scraping a wikipedia page using "BeautifulSoup"

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
page = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(page.content, 'html.parser')

In [4]:
table=soup.find("tbody")
rows=table.select("tr")
row=[r.get_text() for r in rows]

#### Clean the dataframe

In [21]:
df=pd.DataFrame(row)
df1=df[0].str.split('\n',expand=True)
df2=df1.rename(columns=df1.iloc[0])
df3=df2.drop(df2.index[0])
df3.head()

    Postcode           Borough     Neighbourhood
1        M1A      Not assigned      Not assigned
2        M2A      Not assigned      Not assigned
3        M3A        North York         Parkwoods
4        M4A        North York  Victoria Village
5        M5A  Downtown Toronto      Harbourfront

#### Delete cells where borough is not assigned

In [27]:
df4=df3[df3.Borough != 'Not assigned']
df4

       Postcode           Borough             Neighbourhood
3           M3A        North York                 Parkwoods
4           M4A        North York          Victoria Village
5           M5A  Downtown Toronto              Harbourfront
6           M6A        North York          Lawrence Heights
7           M6A        North York            Lawrence Manor
..  ..      ...               ...                       ... ..
282         M8Z         Etobicoke  Kingsway Park South West
283         M8Z         Etobicoke                 Mimico NW
284         M8Z         Etobicoke        The Queensway West
285         M8Z         Etobicoke     Royal York South West
286         M8Z         Etobicoke            South of Bloor

[210 rows x 5 columns]

In [33]:
df5 = df4.groupby(['Postcode', 'Borough'], sort = False).agg(','.join)
df5.reset_index(inplace=True)
df5

,Postcode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,Harbourfront
3,M6A,North York,"Lawrence Heights,Lawrence Manor"
4,M7A,Downtown Toronto,Queen's Park
...,...,...,...
98,M8X,Etobicoke,"The Kingsway,Montgomery Road,Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
101,M8Y,Etobicoke,"Humber Bay,King's Mill Park,Kingsway Park Sout..."
102,M8Z,Etobicoke,"Kingsway Park South West,Mimico NW,The Queensw..."

In [39]:
df5["Neighbourhood"].replace("Not assigned","Queen's Park",inplace=True)
df5.head()

  Postcode           Borough                    Neighbourhood
0      M3A        North York                        Parkwoods
1      M4A        North York                 Victoria Village
2      M5A  Downtown Toronto                     Harbourfront
3      M6A        North York  Lawrence Heights,Lawrence Manor
4      M7A  Downtown Toronto                     Queen's Park

In [41]:
df5.shape

(103, 3)